/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.Color;
import java.util.LinkedList;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author juangabriel
 */
public class Adivinados extends javax.swing.JFrame {

    Player player1;
    Player player2;
    Logica logica;

    /**
     * Creates new form Adivinados
     */
    public Adivinados() {
        initComponents();
        setLocationRelativeTo(null);
        player1 = new Player();
        player2 = new Player();
        btnpinchar.setEnabled(false);
        logica = new Logica();
        btngood.setBackground(Color.green);
        btnerror.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpuntajemaquina = new javax.swing.JTextField();
        txtpuntaje = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtmaquina = new javax.swing.JLabel();
        btnpinchar = new javax.swing.JButton();
        btnerror = new javax.swing.JButton();
        btngood = new javax.swing.JButton();
        lblturn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Preguntados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 226, 34));

        txtname.setBackground(new java.awt.Color(0, 0, 0));
        txtname.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 0));
        txtname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 58, 123, 35));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PUNTAJE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 126, 80, 30));

        jLabel4.setText("JUGADOR:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, 80, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PUNTAJE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 126, 80, 30));

        txtpuntajemaquina.setBackground(new java.awt.Color(255, 255, 255));
        txtpuntajemaquina.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtpuntajemaquina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpuntajemaquina.setText("0");
        txtpuntajemaquina.setEnabled(false);
        txtpuntajemaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpuntajemaquinaActionPerformed(evt);
            }
        });
        getContentPane().add(txtpuntajemaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 123, 65, 40));

        txtpuntaje.setBackground(new java.awt.Color(255, 255, 255));
        txtpuntaje.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        txtpuntaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpuntaje.setText("0");
        txtpuntaje.setEnabled(false);
        txtpuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpuntajeActionPerformed(evt);
            }
        });
        getContentPane().add(txtpuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 123, 65, 40));

        jLabel6.setText("JUGADOR 2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 58, 80, 35));

        txtmaquina.setBackground(new java.awt.Color(0, 0, 0));
        txtmaquina.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        txtmaquina.setForeground(new java.awt.Color(0, 0, 0));
        txtmaquina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtmaquina.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtmaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 58, 141, 35));

        btnpinchar.setBackground(new java.awt.Color(0, 0, 0));
        btnpinchar.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        btnpinchar.setForeground(new java.awt.Color(255, 255, 255));
        btnpinchar.setText("PICHAR");
        btnpinchar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpincharActionPerformed(evt);
            }
        });
        getContentPane().add(btnpinchar, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 331, 108, 57));

        btnerror.setText("ERROR");
        getContentPane().add(btnerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 261, 72, -1));

        btngood.setText("GOOD");
        getContentPane().add(btngood, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 207, 72, -1));

        lblturn.setFont(new java.awt.Font("AnjaliOldLipi", 2, 14)); // NOI18N
        lblturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 400, 190, 29));

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/juangabriel/Imágenes/logo.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 430));

        jMenu1.setText("Comenzar juego");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("STAR");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Intruciones");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Crear Preguntas");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpuntajemaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpuntajemaquinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpuntajemaquinaActionPerformed

    private void txtpuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpuntajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpuntajeActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        String name = JOptionPane.showInputDialog("ingrese  su nombre");
        int puntaje = Integer.parseInt(txtpuntaje.getText().trim());
        player1.setName(name);
        player2.setPuntaje(puntaje);
        logica.stargame(player1, player2());
        txtname.setText(player1.getName());
        

        logica.who_starts();
        if (logica.isX() == true) {
            btnpinchar.setEnabled(true);
            lblturn.setText("Jugando :"+txtname.getText());
            lblturn.setBackground(Color.BLUE);
            logica.turn(logica.isX(), txtname.getText().trim());
        } else {
            Timer timer = new Timer();
            TimerTask task = new TimerTask() {

                @Override
                public void run() {
                    logica.turn(logica.isX(), txtmaquina.getText().trim());
                     btnpinchar.setEnabled(false);
                      lblturn.setText("Jugando : "+txtmaquina.getText());
               
                      btnpinchar.setBackground(Color.BLUE);
                }
            };
            timer.schedule(task, 0, 1000);
             System.out.println("El juego a comenzado");
                 timer.cancel();
          }
   
    }//GEN-LAST:event_none

    private void btnpincharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpincharActionPerformed
       logica.upload_questions();
        LinkedList<preguntas>p= new LinkedList<>();
         p= logica.getLIsta_preguntas();
         int contador=Integer.parseInt(txtpuntaje.getText());
        for (preguntas p1 : p) {
            int respuesta=JOptionPane.showConfirmDialog( null,p1.getPregunta(), "Seleccione",JOptionPane.YES_NO_OPTION);
            if (respuesta==JOptionPane.YES_OPTION) {
                 contador+=1;
            }
            if (respuesta==JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "la respuesta  incorrecta");
            }
        }
       txtpuntaje.setText(String.valueOf(contador));
    }//GEN-LAST:event_btnpincharActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
   crear_Preguntas p= new crear_Preguntas();
      p.setVisible(true);
        dispose();
  
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adivinados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adivinados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adivinados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adivinados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Adivinados().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnerror;
    private javax.swing.JButton btngood;
    private javax.swing.JButton btnpinchar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblturn;
    private javax.swing.JLabel txtmaquina;
    private javax.swing.JLabel txtname;
    private javax.swing.JTextField txtpuntaje;
    private javax.swing.JTextField txtpuntajemaquina;
    // End of variables declaration//GEN-END:variables
public Player player2() {
        player2.setName("marcos");
        txtmaquina.setText(player2.getName());
        player2.setPuntaje(Integer.parseInt(txtpuntajemaquina.getText().trim()));
        return player2;
    }

}
